import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import Hero from '@/components/Hero';
import heroapi from '@/data/data';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="flex flex-col gap-16 relative">
          <Hero heroapi={heroapi} />
        </main>
        {children}
      </body>
    </html>
  );
}
